name: flutter_state_notifier
description: Flutter bindings for state_notifier, such as StateNotifierProvider and StateNotifierBuilder
version: 0.7.3
homepage: https://github.com/rrousselGit/state_notifier

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  provider: ^6.0.0
  state_notifier: 0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
