name: flutter_state_notifier
description: Flutter bindings for state_notifier, such as StateNotifierProvider and StateNotiferBuilder
version: 0.7.0
homepage: https://github.com/rrousselGit/state_notifier

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  provider: ^6.0.0
  state_notifier: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.6
  mockito: ^5.0.0-nullsafety.0
